export default [
  'smsCode',
  'qrcode',
  'phone',
  'captcha',
  // "/open/activity/activity/page",
  // "/open/advertisement/advertisement/list",
  "refreshToken",
  "deviceRegister",
  'param',
  'qrcodeStatus',
  '/app/dict/info/data',
  // '/app/artisanAbility/artisanAbility/list_v1',
  '/app/category/category/list',
  // '/open/artisanAbility/artisanAbility/list_v1',
  // '/open/artisanAbility/artisanAbility/list_v2',
  // '/app/artisanAbility/artisanAbility/list_recommend_v1',
  // '/app/artisanAbility/artisanAbility/list_recommend_v2',
  '/app/wowserver/wowserver/list',
  '/app/user/login/bigfoot',
  '/app/user/login/bigfoot',
  '/app/user/login/phone_bf',
  '/app/user/login/smsCode_bf',
  // "/app/base/comm/uploadMode"
  '/app/track/track/record',
  '/app/category/sectionCategory/list',
  '/app/rank/dpsTopRank/topRank',
  '/app/simc/userSimcRecord/info',
  '/comm/wx/getMiniQRCode',
  '/comm/wx/getMiniURLScheme',
]