export const STORAGE_KEY = {
  TOKEN: 'TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  EXPIRE: 'EXPIRE',
  REFRESH_EXPIRE: 'REFRESH_EXPIRE',
  USER_DEVICE_ID: 'USER_DEVICE_ID',
  CHAT_USER_LIST: 'CHAT_USER_LIST',
  WINDOW_CHAT_QUERY: 'WINDOW_CHAT_QUERY',
  DEVICE_ID: 'DEVICE_ID',
  FROM_REF: 'FROM_REF',
  SERVER_NAME_HISTORY: 'SERVER_NAME_HISTORY',
  LAST_SEARCH_SERVER_NAME: 'LAST_SEARCH_SERVER_NAME',
  CLIENT_ID: 'CLIENT_ID',
  IS_OPEN_GUIDE: 'IS_OPEN_GUIDE',
  SIMC_STRING: 'SIMC_STRING', // 模拟器字符串
  IS_FIRST_USE_GEAR: 'IS_FIRST_USE_GEAR', // 是否第一次使用
  HAD_USE_GEAR_PAGE: 'HAD_USE_GEAR_PAGE', // 是否第一次使用
}
